- templates/page.mustache
Because we don't intend to support compat modes.
> Demos: force edge mode in IE

- README.md
- lib/tasks/build.js
I would like to have this options for Next as we need to have sourcemaps on production so that errors are tracable.
The sourcemaps config option can be a boolean
``` sourcemaps : true```
or an object ie
```sourcemaps : {
sass : false,
js : true
}```
As we can't yet have sass sourcemaps the 2nd method is pointless so I haven't documented it.
> Adding sourcemaps option

- package.json
> Fix dependency error on windows by using a different git URL syntax

- README.md
- config/jshint.json
- lib/tasks/build.js
For next we want to have sourcemaps in production - this option will make this possible as then we can perform the minification ourselves.
You can specify `true` `false` or object ie: `{js:false,sass:true}`
If the compress option is not specified it falls back to the default behaviour.
> Adding compress option

- lib/tasks/build.js
- package.json
I came across an error whereby the build task reports itself as finished long before it actually has:
This makes it impossible to correctly chain other gulp tasks after obt.build.
Now the build method returns a merged stream of the 2 build tasks and this fixes the error:
> returning merged stream from build task

- lib/tasks/build.js
- lib/tasks/demo.js
- lib/tasks/test.js
Works only with Sass 3.4
@alberto:
I see we're using `getCommandVersion('sass', '--version')` in `getInstalledSassGemVersion`.
It'd be great to make that reusable inside build.js and demo.js so that we can do something like:
```js
var sassVersion = getInstalledSassGemVersion();
if (semver.lt(sassVersion, '3.4')) {
sassConfig["sourcemap=none"] = true;
}
```
And then this branch would work in both Sass 3.3 and 3.4.
> [Sass 3.4] Disable sourcemaps

- lib/tasks/build.js
Debowerify uses esprima to parse the code which doesn't (yet) support ES6, so 6to5 needs to run first
> changing order of browserify transforms

- lib/tasks/install.js
- Be clearer in the reference about hyphen/underscore equivalence.
- @keyframes rules are now converted from CSS properly.
- Extending a selector that contains a non-final pseudo-class no longer crashes.
- When @extending, only a single :root element will be retained.
> Update to latest version of Sass

- lib/tasks/install.js
This is breaking all builds of this version of OBT on Next…  (seriously)
> Undo `--loglevel info`

- README.md
- lib/helpers/log.js
- lib/origami-build-tools-cli.js
- lib/origami-build-tools.js
Introduce a TaskLoader for loading tasks.
Introduce a new log level 'debug' (which is defaulted to 'off').  To turn it on run `DEBUG=true obt task`.
The main reason to introduce the DEBUG=true log level is to surface performance issues and help spot issues, if any are low hanging fruit, and easy to fix, we can fix them in the right place.
> #perfmatters

- package.json
It does not support synchronous mode, which caused an external dependency to be required, which required native compilation - sloooow stuff for stuff we don't even use.
> Use this version of gulp-scss-lint 

- README.md
- TROUBLESHOOT.md
- config/scss-lint.yml
- lib/tasks/install.js
Thanks to the latest version of SCSS-Lint, we can exclude certain non-standard properties that require vendor-prefixes so that they won't raise warnings anymore:
- user-select
- font-smoothing
Fixes https://github.com/Financial-Times/ft-origami/issues/343
> Update to latest version of SCSS-Lint and allow vendor prefixes for certain properties

- README.md
- lib/tasks/build.js
- lib/tasks/demo.js
- package.json
This has a dependency on a fork of `textrequireify`, waiting for that to get merged and published to NPM.  Don't merge before I've updated the `package.json` here for it.
This is a breaking change as it alters the API for configuring browserify transforms.
> Update browserify dependency

- package.json
It now uses [sync-exec](https://www.npmjs.com/package/sync-exec), an fs.execSync replacement until you get it natively from node 0.12+.
@samgiles I think your fork is better than this version but I believe it's probably better to follow the main project instead of relying on our own forks.
> Go back to using the official scss-lint gulp task

- README.md
After recently going through the install process and having this specific issue, I can vouch that the problem occurs with npm > 2.7.5.
> Fix typo within npm version notice.

- lib/tasks/install.js
I can't think of a case where wanting the stderr of a `--version` call would ever be useful……
Also because ruby is corrupted on Next's Jenkins machine (cc @captain-sysadmin) this means OBT doesn't work for any of our Stash repos :-(.
> Suppress stderr when getting the version of a command

- .npmignore
I don't think you tested this :-)
if you try to do `obt verify` you get this error:-
```
/Users/mandrews/sandboxes/next-build-tools/node_modules/origami-build-tools/node_modules/gulp-eslint/node_modules/eslint/lib/config.js:78
throw e;
^
Error: Cannot read config file: /Users/mandrews/sandboxes/next-build-tools/node_modules/origami-build-tools/config/.eslintrc
Error: ENOENT, no such file or directory '/Users/mandrews/sandboxes/next-build-tools/node_modules/origami-build-tools/config/.eslintrc
```
because `.npmignore` is stopping that file from being published to the registry
> let npm publish obt with `.eslintrc`

- lib/tasks/build.js
- package.json
Re-doing #310 against master, since updating it with ES6 has led to a very messy thread.
Essentially this is for the purpose of allowing lpiepiora/bower-webpack-plugin#27 to handle the resolution directory for OBT, so that custom module directories are respected.
> Allow Bower Plugin to resolve default bower_components directory

- lib/tasks/build.js
If sass outputs compressed then any autoprefixer comments are stripped out. This change outputs verbose css from sass. As cssclean runs after autoprefixer the css does end up getting minified anyway.
As a small bonus, this will probably make the build slightly quicker
> Preserve autoprefixer comments

- package.json
`babel-core` is a peer dependency of `babel-loader`, and as per what's recommended in npm v2 (and required in v3), can we explicitly depend on it
> Explicitly require babel-core peer dependency

- lib/tasks/build.js
Error occurs when no JS or Sass stream is returned. Check if stream returned is not `undefined` before assigning the event handler.
> fix error when no JS or Sass streams are returned

- README.md
- lib/tasks/test.js
- test/tasks/build.test.js
Added a new flag `browserTestFailBuild` to allow failed browser tests to fail the build on CI.
The build of o-ads without new flag:
https://circleci.com/gh/Financial-Times/o-ads/45 - note that tests failed but build passed
The build of o-ads with new flag:
https://circleci.com/gh/Financial-Times/o-ads/46 - note tests failed and build failed
Both builds point to the the new branch
/cc @AlbertoElias @alicebartlett
> Optionally allow failed browser tests to fail CI

- lib/tasks/build.js
- package.json
This allows the following:
`const template = require('templates/foobar.html')`
where template will become `<h1>Hello world</h1>` if the contents of `templates/foobar.html` is `<h1>Hello world</h1>`.
If people wish to continue and use `requireText`, they can do so. This doesn't break `requireText`. This simply tells `webpack` what to do if it sees a `require('....html')`.
> add a raw loader for HTML requires

- lib/tasks/build.js
That’s to get the webpack to use NODE_ENV=‘production’ in build - most notably this is a requirement for React to use their super-minified version.
> get webpack to use NODE_ENV='production' in building if in production

- templates/page.mustache
Makes it use the same example as the spec: http://origami.ft.com/docs/developer-guide/modules/core-vs-enhanced-experience/#add-styles-to-hide-core-only-html-in-origami
> Uses !important in ctm css

- lib/tasks/verify.js
- test/fixtures/o-test/origami.json
- test/tasks/verify.test.js
Add a failing test for the verify task which looks for the expanded property in component demos.
Do not merge until the new Registry has been deployed.
> Deprecate the expanded property for demos

- lib/helpers/metrics.js
- lib/origami-build-tools.js
- package.json
- test/origami-build-tools.test.js
This makes a start to addressing #390.
This adds Graphite reporting capabilities and uses them to track the major version of node being used when executing OBT whether from the command line or programatically.
> Add feature: Analytics

- package.json
Adding this means people no longer have to install PhantomJS separately to run Pa11y tests.
This can be removed if the PR to Pa11y is merge -- https://github.com/pa11y/pa11y/pull/190
> Add phantomjs-prebuilt for pa11y to work without extra set-up steps

- lib/helpers/metrics.js
- test/helpers/metrics.test.js
Without this, the node process would not close until the tcp connection automatically closes itself.
> close the socket once a write is completed

- .travis.yml
- README.md
Node 5 is no longer supported by Node, we should also no longer support Node 5 and concentrate on Node 4 and Node 6 until October.
> Let node 5 fail on CI

- lib/helpers/command-line.js
- package.json
- test/helpers/command-line.test.js
Same as #418 but for OBT version 5 instead of OBT version 6.
You can view the diff against v5.5.5 here --> https://github.com/Financial-Times/origami-build-tools/compare/v5.5.5...magic-v5
> Backporting - Pipe command output to stderr/stdout whilst keeping same interface - v5

- config/scss-lint.yml
The scss-lint config passes an invalid option and so this message appears:
> The border-zero convention `zero` in your config file is not valid. Defaulted to convention `0`
This changes `zero` to simply `0` as per [the docs](https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md#borderzero).
> 🐛 Fixes invalid scss-lint config option

- lib/origami-build-tools-cli.js
No longer needed now that we use `meow`.
> Remove the version hack

- lib/tasks/build.js
Safari version 8 requires the prefixed version of flexbox to work successfully.
Fixes https://github.com/Financial-Times/o-teaser/issues/49
> Add Safari 8+ to autoprefixer config

- lib/tasks/verify-origami-json.js
- lib/tasks/verify.js
- test/tasks/verify-origami-json.test.js
- test/tasks/verify.test.js
This starts the work off for moving the `obt verify` task to using the Listr module. I have also separated out the Origami verification tasks to a separate file to make it simpler to understand what dependencies it is using, this is what has also been done for the `obt test` task in the past.
> Move verify origami task to new file and add lots of tests

- lib/tasks/demo.js
- test/tasks/demo.test.js
Origami used to allow a JS file to be used to configure Origami demos. We are removing this as it can be abused to run arbitrary code within the origami-build-tools process.
> Remove old way of specifying demos using javascript.

- lib/tasks/build.js
n-webpack uses handlebars to compile .html files and obt uses the raw-loader to return the html as a string. This caused issues on o-comments as handlebars returns a function instead of a string.
To avoid this confusion, we have both agreed to use .txt to signify require calls which should return strings of the file being required.
This PR and a PR to change o-comment-ui to use .txt instaed of .html will mean that next-article can be updated to the new origami components! 🎉
> use raw-loader for .txt files

- README.md
- lib/origami-build-tools-cli.js
I'm always typing `obt i` wanting `obt install` and `obt d` for `obt demo`. I figured supporting them wouldn't require much extra work and that the benefit outweighs that extra work.
@rowanmanning what do you think?
> Enable commands such as `obt i` to work

- lib/tasks/demo-build.js
- package-lock.json
- package.json
- test/tasks/demo-build.test.js
In some cases we would like to use external data when building component demos so our demos match reality. For example in `o-footer`:
https://github.com/Financial-Times/o-footer/issues/81
For reliability of build this should be used sparingly. The `o-footer` example would depend on the navigation service, a "platinum" application.
E.g `origami.json` `demos` config using a remote data source (new ability):
```
{
"name": "footer",
"title": "Dark theme",
"template": "demos/src/footer-dark.mustache",
"data": "https://www.ft.com/__origami/service/navigation/v2/menus/footer/?source=test",
"description": "This is the standard masterbrand footer used on most pages."
}
```
E.g `origami.json` `demos` config using a local data source (current):
```
{
"name": "footer",
"title": "Dark theme", …
```
> Allow remote demo data

- README.md
We are doing this to ensure that when ES Modules land, our components work correctly :-) The previous solution was not following the specification
> Add section about es6 modules difference with obt6

- config/karma.config.js
- lib/tasks/karma.js
Some components such as o-ads-embed have their test files end in `.spec.js`, as the suffix for test files is not specified in the origami specification, we should allow any suffix to exist.
> Allow test files to have any name ending in .js

- lib/tasks/demo.js
We have a few components which have no demos such as o-autoinit. This will stop `obt demo` from attempting to compile any demos for such components.
> Don't attempt to compile demos if no demos exist

- .travis.yml
Node 8 has been out for a while now, we should ensure that obt works with it
> Run tests on node8

- lib/helpers/listr-renderer.js
- package-lock.json
- package.json
Example of the verbose renderer when used for `obt test`:
```
[12:28:58] Testing SCSS silent styles [started]
[12:28:58] Testing SCSS silent styles [completed]
[12:28:58] Executing `npm test` [started]
[12:28:58] Executing `npm test` [skipped]
[12:28:58] Executing Pa11y [started]
[12:28:58] Executing Pa11y [skipped]
[12:28:58] → No Pa11y demo found. To run Pa11y against this project, create a file at /Users/jake.champion/Code/work/origami/components/o-forms/demos/local/pa11y.html
[12:28:58] Running Karma tests [started]
[12:28:58] Running Karma tests on Chrome Stable [title changed]
[12:28:58] Tests starting... [started]
[2017-10-09 12:28:59.326] [DEBUG] config - Loading config /Users/jake.champion/Code/oss/origami-build-tools/config/karma.config.chrome.js
[12:28:59] Starting Karma server …
```
> Use a verbose renderer for CLI output when running in a CI environment

- test/unit/plugins/listr-karma.test.js
The color sequences are appearing in the tests. I've wrapped the test
strings with the expected color method, which means they should match
whether or not escape codes are added.
> Include bash color sequences in the tests

- config/webpack.config.js
- package-lock.json
- package.json
This is used for Origami Build Service. When installing Origami Build Tools as a dependency, it's dependencies are deduped by npm which causes the loaders to not be found because they are no longer under the origami-build-tools folder (they are within the consuming applications node_modules folder).
> Enable loaders to be resolved from a consuming applications node_modules folder

- lib/tasks/verify-origami-json.js
- test/unit/fixtures/o-test/origami.json
- test/unit/tasks/verify-origami-json.test.js
Inline with the Origami spec and registry expectations.
All actively maintained Origami maintained `isOrigami` components should be covered when the PRs created today are merged. Deprecated or non-origami-maintained components will get caught by this new `obt verify` requirement.
Does this effect the build service?
> Require demo titles in origami.json.

- lib/helpers/command-line.js
- lib/tasks/test-sass.js
`npx origami-build-tools test` currently fails because `execa` can not find `mocha`. This is because `npx` installs modules into a directory that `execa` doesn't look into. We can tell `execa` where to look using the `localDir` option.
> Make obt test work with npx

- lib/tasks/build-sass.js
> Reformat SASS build error to include file, line, and column.

- lib/helpers/files.js
SCSS tests are not discovered currently (e.g. [o-brand tests](https://github.com/Financial-Times/o-brand/tree/master/test/scss)).
> Update True SCSS tests path.

- .circleci/config.yml
As per the docs -- https://circleci.com/blog/publishing-npm-packages-using-circleci-2-0/#git-tag-job-execution---deploy-on-tagged-commit
> Fix publishing from circle ci 2

- .snyk
- lib/origami-build-tools-cli.js
`obt demo --run-server --port=3002`
Requested for `o-ads`, to run custom tests against browserstack which requires a certain port for IOS: https://www.browserstack.com/question/664
> Add port flag to obt.

- lib/tasks/sass.js
Now:
>When compiling with `$o-footer-services-is-silent: false;` no styles were output when the should have been: Failed building SASS:
'null' is not a valid base color.
Previous:
>When compiling with `$o-footer-services-is-silent: false;` no styles were output when the should have been
> Make the error message for the silent mode test more helpful.

- lib/tasks/boilerplate.js
- templates/boilerplate.js
- templates/component-boilerplate/migration.js
- templates/component-boilerplate/read-me.js
This adds the MIGRATION.md to the boilerplate, and updates the README with the MIT license badge (now that all of our components seem to have it), removes some weird lines and adds an example of the migration table.
> update readme, add migration

- templates/component-boilerplate/origami-json.js
Currently `obt init` generates an `origami.json` file that specifies a
support status of "active" and support contact details which point to
the Origami team.
This means that the responsibility for marking a new component as
experimental or maintained by another team is on the person creating a
component. This makes work for us, as we have to remind a non-Origami
developer to update these fields before publishing, and it's possible
(even likely) that an unsupported component will appear in the registry
as "actively maintained by the Origami team".
This PR updates the template to provide sensible details for users who
aren't as familiar with Origami. Members of the Origami team who create
new components are more likely to check and update this information as
required without prompting.
> Update the default support details

- .circleci/config.yml
- package-lock.json
The master branch had a package-lock.json which was out-of-sync with package.json, we can ensure that never happens by using `npm ci` in CircleCI instead of `npm i`. Using `npm ci` has an added benefit of simplifying the CircleCI config because it guarantees that the node_modules folder will be the same.
> Let's use npm ci instead of npm i

- config/karma.config.js
- lib/tasks/test-sass-compilation.js
OBT always tests component SCSS can compile for the master brand, because it used to be required. However that isn't true anymore, so OBT should only test compilation for brands specified within a component's `origami.json`.
> Only build supported brand SCSS

- templates/component-boilerplate/ci-config-yml.js
There's a possible future when a `bower.json` might not exist in the repo !
> Ensure bower.json exists for caching, too

- lib/plugins/silent-sass.js
- test/unit/plugins/silent-sass.test.js
Since introducing branded components it is possible for a CSS build to have no content. For example [see o-fonts](https://github.com/Financial-Times/o-fonts/pull/90), where the whitelabel brand outputs no font faces by default but its scss mixins are still useful. With this update OBT will no longer error when CSS is built with no content. Instead we can use [True](https://github.com/oddbird/true) within our components to validate output.
I can't think of a good alternative, except for complicating origami.json to indicate when we expect output or not. 😷
> Allow SCSS builds with no content.

- config/karma.config.js
Fixes `obt test` which is failing builds as JS dependencies do not resolve correctly. E.g:
https://circleci.com/gh/Financial-Times/o-table/414?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link
>Uncaught Error: Cannot find module "dom-delegate"
> Fix obt test.

- lib/tasks/demo-build.js
We do this in [an old version of OBT](https://github.com/Financial-Times/origami-build-tools/compare/v5.7.1...v5.8.0) which the build service uses, but not in the newer version of OBT. Save us OAT 🙈
> Add brand query param to demo dependencies.

- templates/component-boilerplate/origami-json.js
- templates/component-boilerplate/src-js.js
We support IE11, which does not support `Array.from` without
a polyfill.
> Remove `Array.from` from the boilerplate JS.

- lib/tasks/karma.js
----
Before this, the browserstack tests would print:
``` text
❯ Running Karma tests on BrowserStack
✖ Starting Karma server
→ Failed Karma tests:
→
→
```
and then fail :(((((((
now it prints this!:
``` text
❯ Running Karma tests on BrowserStack
✖ Tests starting...
→ Required environment variables (BROWSER_STACK_USERNAME, BROWSER_STACK_ACCESS_KEY) not supplied
```
and then fail :)))))))))
> Print a helpful error if the user hasn't supplied required keys

- config/karma.config.browserstack.js
Mostly the same as this, except without Samsung browser (we can't) and using iOS
Safari 10 instead of iOS Safari 9 (we can't test iOS 9)
https://docs.google.com/document/d/1AG4uZEFiWOkXfy0pdE3-3NCUP2No4MkoiZMLlJnO5lI/edit?ts=5d498574
> Upgrade minimum browser versions to match doc enhanced support

- lib/tasks/build-sass.js
Soon our components will require a `$system-code` variable to build. 
e.g. https://github.com/Financial-Times/o-footer-services/issues/10
Set the system code to `origami-build-tools` when working on components locally.
> Set the system code variable when building Sass.

- lib/tasks/build-sass.js
> Make Sass errors more useful.

- templates/component-boilerplate/src-sass-mixins.js
Relates to proposal: https://github.com/Financial-Times/origami-proposals/issues/4
And the major cascade project, where we are removing custom Sass classes:
https://github.com/orgs/Financial-Times/projects/77
> Remove custom class name variable from Sass boilerplate.

- lib/helpers/construct-polyfill-url.js
- test/unit/helpers/construct-polyfill-url.test.js
Otherwise this can give the false impression a component works
in a browser without polyfills. Only polyfills requested in
`origami.json` (`browserFeatures.required`) should be included.
https://github.com/Financial-Times/origami-build-tools/issues/622
> Only include explicitly required polyfills in demos.

- lib/tasks/demo.js
- package-lock.json
- package.json
Otherwise this can give the false impression a component works
in a browser without polyfills. Only polyfills requested in
`origami.json` (`browserFeatures.required`) should be included.
https://github.com/Financial-Times/origami-build-tools/issues/622
This backport to v5 brings this change to the Build Service demos.
> v5 backport: Only include explicitly required polyfills in demos.

- lib/helpers/files.js
This doesn't work because the post-occ's npm name is `@financial-times/whatever`
> Revert "Fallback to npm name if bower name is missing"

- lib/tasks/demo-build.js
- test/unit/tasks/demo-build.test.js
Builds are asynchronous, and would previously all start before
the flag which prevents multiple of the same build was set.
o-buttons, which has a lot of demos, builds around ~4.5s instead
of ~36.65s. Making it about ~7.85 times faster! :ta-da:
> Only build Sass once when shared by multiple demos.

- package-lock.json
- package.json
- test/integration/build/build.test.js
- test/unit/tasks/build-sass.test.js
This fixes the error `decl.moveTo is not a function` that we are seeing in lots of CI builds which are using `obt build --production` -- https://circleci.com/gh/Financial-Times/origami-registry-ui/980
> update to latest cssnano

- package.json
v2 to v4 does not seems to impact origami-build-tools.
v4: https://github.com/janl/mustache.js/blob/master/CHANGELOG.md#400--16-january-2020 TLDR;
- if your project manipulates Writer.prototype.parse | Writer.cache directly
or uses .to_html(), you probably have to change that code.
v3: https://github.com/janl/mustache.js/blob/master/CHANGELOG.md#300--16-september-2018 TLDR;
- #618: Allow rendering properties of primitive types that are not objects
- #643: Writer.prototype.parse to cache by tags in addition to template string
- #664: Fix Writer.prototype.parse cache
> Upgrade mustache.js

- README.md
- config/webpack.config.js
- package.json
All default CommonJS imports will now have a `.default` property.
See: https://github.com/Financial-Times/origami-build-tools/issues/609
> Remove `babel-plugin-add-module-exports`

- lib/tasks/test-sass.js
- package-lock.json
- package.json
true-sass now supports dart-sass, but let's stick with node-sass
for True testing until we get rid of node-sass compilation tests
https://github.com/oddbird/true/blob/master/CHANGELOG.md#true-changelog
(just to avoid including three separate Sass implementations)
> Upgrade true-sass.

- package-lock.json
- package.json
deglob stopped testing on non-LTS NodeJS versions which is why they increased the major version
> update deglob to latest version

- package-lock.json
- package.json
breaking changes:
v11.0.0
Require Node.js 10 4a471af
Get rid of glob dependency (#135) d4681a4
If you passed in options to globby.hasMagic(), you need to update to use the new options.
v10.0.0
Upgrade fast-glob package to v3 (#126) 3706920
Important: Read the fast-glob release notes! There are many breaking changes.
Require Node.js 8 9f781ce
Remove **/bower_components/** as a default ignore pattern 2dd76d2
v9.0.0
Require Node.js 6 and upgrade dependencies 8815ee8
Rename the opts property returned from .generateGlobTasks to options c1c744d
v8.0.0
We have replaced node-glob with fast-glob (ba08350), as fast-glob is a lot faster and better maintained. This will impact you if you passed in any node-glob specific options.
v7.0.0
Requires Node.js >=4
Added expandDirectories option which is on …
> update globby to latest version

- package-lock.json
- package.json
breaking changes from karma-chrome-launcher:
allow overriding of the default debug port
> update karma-chrome-launcher to latest version

- package-lock.json
- package.json
breaking change from karma-scss-prepocesser:
Upgraded minimum NodeJS version to 6
> update karma-scss-preprocessor to latest version

- package-lock.json
- package.json
breaking change from through2:
readable-stream@3 is now being used which does not support Node@8 or below
> update through2 to latest version

- package-lock.json
- package.json
log-symbols breaking changes:
Require Node.js 8 e1542f5
> update log-symbols to latest version:

- config/webpack.config.dev.js
- config/webpack.config.prod.js
- package-lock.json
- package.json
breaking changes from karma-webpack:
4.0.0
default: minimum required nodejs version is 8.9
3.0.0
package: requires webpack >= v2.0.0
package: requires node >= 6.9.0
> update karma-webpack to latest version

- lib/tasks/boilerplate.js
- package-lock.json
- package.json
- templates/boilerplate.js
- templates/component-boilerplate/eslint-ignore.js
parse-gitignore v1 breaking change is that it no longer attempts to turn ignores into globs.
We never used that behavior though :-)
> update parse-gitignore to latest version

- package.json
v4 BREAKING CHANGES
- Drop Support for Node 6, to make it possible to use async/await in karma codebase.
v3 BREAKING CHANGES
- Drop Support for Nodejs4 (#3082)
> Upgrade Karma

- package.json
Drops support for node 4 and 0.10.
https://github.com/grncdr/merge-stream/compare/v1.0.1...v2.0.0
> Upgrade merge-stream

- lib/tasks/demo-build.js
- package-lock.json
- package.json
- test/unit/tasks/demo-build.test.js
- Our components do not use remote demo data.
- o-header could use this feature to show up-to-date links from
the Navigation Service, but if users copy/paste their navigation
will become out of date. Instead we should use dummy data
(https://github.com/Financial-Times/o-header/issues/160)
- The Origami specification says "if [the demo field] is a string
it must be a path to a JSON file containing the data, relative to
the root of the repo." So remote data is not allowed by the spec.
(Let's not worry about the effort I went to in a previous commit,
to replace `request-promise-native` with `node-fetch`.)
> Remove remote demo data feature.

- config/karma.config.js
- package-lock.json
- package.json
instead of abusing webpack to make proclaim available via import/require.
https://github.com/Financial-Times/origami-build-tools/blob/cf219aa5029754feb0f98c63db87f2af4a439786/config/webpack.config.dev.js#L6-L9
> use karma-proclaim to make proclaim a global variable used in tests

- lib/tasks/build-sass.js
- test/unit/tasks/build-sass.test.js
We were using our `log.debug` method to output Sass debug and
warning messages, which is only logged when the enviroment variable
`OBT_LOG_LEVEL` is set to `debug`. We are not debugging the build
tools themselves and so should use the `log.secondary` method
instead.
> Always output Sass debug messages with the verbose flag.

- lib/tasks/demo-build.js
Missed this bit in https://github.com/Financial-Times/origami-build-tools/pull/738
> Pass --ignore-bower flag from command line to demo-build

- README.md
- lib/origami-build-tools-cli.js
- lib/tasks/build-sass.js
This is part of the work for https://github.com/Financial-Times/origami-build-tools/issues/735
- Removed the `--js` flag.
- Removed the `--sass` flag.
- Removed the `--build-js` flag.
- Removed the `--build-css` flag.
- Removed the `--build-folder` flag.
- Removed the `--standalone` flag.
- Removed the `--verbose` flag.
> Remove flags we no longer want to support

- README.md
- lib/origami-build-tools-cli.js
Replaces:
`obt demo --run-server --watch --verbose --brand=internal`
With:
`obt dev --brand=internal`
https://github.com/Financial-Times/origami-build-tools/issues/735
> Add new `develop` command. Remove `watch` and `run-server` flags.

- lib/helpers/construct-polyfill-url.js
- lib/tasks/demo-build.js
- templates/page.mustache
- test/integration/demo/demo.test.js
- test/integration/demo/fixtures/multiple-demos/bower.json
- test/integration/demo/fixtures/multiple-demos/demos/src/demo-1.mustache
- test/integration/demo/fixtures/multiple-demos/demos/src/demo-2.js
- test/integration/demo/fixtures/multiple-demos/demos/src/demo-2.mustache
- test/integration/demo/fixtures/multiple-demos/demos/src/demo-2.scss
- test/integration/demo/fixtures/multiple-demos/demos/src/demo.js
- test/integration/demo/fixtures/multiple-demos/demos/src/demo.scss
- test/integration/demo/fixtures/multiple-demos/demos/src/pa11y.mustache
- test/integration/demo/fixtures/multiple-demos/main.js
- test/integration/demo/fixtures/multiple-demos/main.scss
- test/integration/demo/fixtures/multiple-demos/origami.json
- test/integration/demo/fixtures/multiple-demos/src/js/o-multiple-demos.js
- test/integration/demo/fixtures/multiple-demos/src/scss/_brand.scss
- test/integration/demo/fixtures/multiple-demos/src/scss/_variables.scss
- test/unit/helpers/construct-polyfill-url.test.js
The polyfill url in demos includes the `default` set, which we
had intended to remove to ensure we catch errors where a
JavaScript feature is not supported by the browser. Only polyfills
which have been explicitly specified in `origami.json` should be
included in demos.
However we only removed the `default` set for Karma tests by mistake:
https://github.com/Financial-Times/origami-build-tools/pull/623
> Add demo command tests and fix a related bug.

- lib/tasks/build-sass.js
- lib/tasks/demo-build.js
- test/unit/tasks/build-sass.test.js
We removed the `--verbose` flag but did not set `verbose: true`
by default. In other words, the `verbose` option still existed
but had no cli flag to set it to true.
Remove the verbose option all together and update our unit tests
to always expect debug output from Sass builds
> Always show Sass debug and warning notices.

- package-lock.json
- package.json
**Move `stylelint-order` to `dependencies` from `devDependencies`**
`obt verify` errors when installed globally, as `stylelint-order` cannot be found. I assume this is why.
**Remove `is-es5-syntax` as a dev dependency, as it is not used.**
> Move `stylelint-order` to `dependencies` from `devDependencies`

- package-lock.json
- package.json
- test/unit/fixtures/verify/src/scss/mixins-before-declarations/valid.scss
`oGridRespondTo` outputs a media query.
> Allow `oGridRespondTo` after declarations when linting Sass.

- package-lock.json
- package.json
- test/unit/fixtures/verify/src/scss/space-after-colon/valid.scss
- test/unit/fixtures/verify/src/scss/space-between-parens/valid.scss
This is useful for formatting functions with large arguments in a
readable way:
```scss
$some-very-very-very-large-conditional: true;
$foreground-color: if(
$some-very-very-very-large-conditional == true,
"then each argument should go on a newline for readability",
"otherwise each argument could be on the same line"
);
```
And for formatting declarations such as grid areas in a readable
way:
```scss
.foo-grid {
grid-template-areas:
"header header header"
". sidebar ."
". main ."
"footer footer footer";
}
```
> Update Sass linting to allow newlines in declarations and functions.

- lib/karma-scrumple.js
- package-lock.json
- package.json
because we're updating the tool to align with [the spec](https://origami.ft.com/spec/v1/components/#npm), we will release it as a patch.
> Use scrumple's new --allow-npm-dev-deps argument

- lib/origami-build-tools-cli.js
> Print previous port number than `true`

- lib/tasks/build-sass.js
- test/unit/tasks/build-sass.test.js
For example, whilst running compilation tests:
https://github.com/Financial-Times/origami-build-tools/pull/780
> Allow Sass sourcemaps to be disabled.

- config/karma.config.js
- lib/karma-scrumple.js
- lib/plugins/listr-karma.js
- lib/tasks/karma.js
- test/unit/plugins/listr-karma.test.js
- test/unit/tasks/pa11y.test.js
problem matchers are used to capture errors from the CI output and put the errors as comments on the lines which correspond to the error.
Here is what the CI reporter looks like when tests fail.
```
[17:53:15] Completed tests on HeadlessChrome 83.0.4103 (Mac OS X 10.15.4) in 20.761 seconds. Ran 102 tests. 95 tests successful. 7 tests failed. Failed Karma tests: 
HeadlessChrome 83.0.4103 (Mac OS X 10.15.4) failed specs:
/Users/jake.champion/Code/repo-data-cli/repos/o-table/test/BaseTable.test.js:1812:15 BaseTable > addSortButtons > adds buttons in the table column headers
HeadlessChrome 83.0.4103 (Mac OS X 10.15.4) errored with: AssertionError: Expected 5 buttons, 1 within each of the 5 column headers.
/Users/jake.champion/Code/repo-data-cli/repos/o-table/test/BaseTable.test.js:1861:15 …
```
> When running in CI, make the mocha reporter easier to work with for problem matchers.

- lib/tasks/pa11y.js
Axe finds issues our previous runner did not. This includes issues
we expect to see in pa11y demos. For example multiple footer
landmarks are ok when testing multiple variants of `o-footer`
e.g. https://github.com/Financial-Times/o-footer/pull/141
> Ignore some axe rules when running pa11y

- lib/tasks/pa11y.js
This change will stop all the pa11y failures we currently see which are for
> make pa11y ignore region rules

- lib/plugins/listr-karma.js
- test/unit/plugins/listr-karma.test.js
When a test fails due to a timeout, we do not get given the file information for where the test originated from. Which means we can not add a good annotation to the pull-request
> Only add karma annotations when we know which file to add them to

- lib/tasks/verify-javascript.js
- test/integration/verify/fixtures/js-custom-eslint/.eslintrc.js
- test/integration/verify/fixtures/js-custom-eslint/main.js
- test/integration/verify/verify.test.js
As per the Origami specification:
https://github.com/Financial-Times/origami-website/blame/49e27d162ca28b212512e128d7987d9a58ee38b7/_specification-v1/javascript.md#L24
> Allow components to define custom `.eslintrc.js` configuration.

- .github/workflows/test.yml
because [engines](https://github.com/Financial-Times/origami-build-tools/blob/master/package.json#L11) says we support 12+
> Test on 12.x and 14.x

- lib/tasks/init.js
closes #864
The previous version of `obt init` was using `npm init origami-component` so there was an invisible dependency.
now we depend on a version range explicitly so we can use that version.
> use our version of create-origami-component

- package-lock.json
- package.json
- test/unit/fixtures/verify/src/scss/no-duplicate-properties/valid.scss
It appears a later version has introduced a regression.
In this `o-header` PR an ignore comment is not recognised.
```
transform: translate3d(-100%, 0, 0); // stylelint-disable-line declaration-block-no-duplicate-properties
```
https://github.com/Financial-Times/o-header/pull/395/
> Pin styleint to a previous version.

- test/integration/demo/fixtures/multiple-demos/main.js
- test/unit/fixtures/o-test/main.js
relative imports require the full path including the extension because browsers use the import name to make a network request and they do not implicitly add a .js file extension if one is missing
> add extension to relative imports to make the code work directly in a browser

- lib/helpers/construct-polyfill-url.js
- test/unit/helpers/construct-polyfill-url.test.js
So demos with dev dependencies work in older browsers. This is because the
Origami Build Service includes `o-autoinit` which requires the `CustomElement`
polyfill.
This has come up because we stopped including the "default" set of polyfills
which included `CustomElement`.
https://github.com/Financial-Times/origami-build-tools/pull/623
We could solve this in a better way, issue here:
https://github.com/Financial-Times/origami-build-tools/issues/906
> Include the `CustomEvent` polyfill in all demos

- config/karma.config.browserstack.js
- config/karma.config.js
- lib/karma-swc.js
currently we are not compiling to ES5 and so the code will not execute in IE11
> When testing with Karma compile the  code to es5 to run in IE11

- config/karma.config.js
- package-lock.json
- package.json
Our compiler (swc) add `require('regenerator-runtime')` to it's output when compiling an async function. We need to add regenerator-runtime as a dependency to obt and include it in the bundle output for tests in order for them to run in older browsers such as IE11.
> Add regenerator runtime to ensure async functions work when compiled to es5

- MIGRATION.md
- README.md
- lib/tasks/test.js
by having `obt test` call `npm test` we are stopping our components from having `obt test` within their `npm test` script.
If we stop calling `npm test` from within `obt test` then we can can add `obt test` within each components `npm test` script, thereby making `npm install && npm test` work for our components.
I think I've worded this poorly, sorry everyone.
With the current obt, this would be an infinite loop:
```json
{
"scripts": {
"test": "obt test"
}
}
```
If this pull-request is merged then the above configuration would work.
> do not call npm test from within obt test

- templates/page.mustache
Partially reverts: https://github.com/Financial-Times/origami-build-tools/pull/814
Demos which rely on `o.DOMContentLoaded` are broken locally.
This revert means component demos may run unsupported JavaScript
in browsers we do not support outside the core experience. Its
been that way for a long time though so this revert doesn't
feel problematic whilst we focus on a new way of writing demos:
https://github.com/Financial-Times/origami/issues/82
> Remove core/enhanced demo.

- lib/tasks/pa11y.js
- test/unit/tasks/pa11y.test.js
This allows component which are built for a single brand to have a pa11y demo which works.
Solves - https://github.com/Financial-Times/origami-ci-tools/issues/23 and https://github.com/Financial-Times/o-meter/issues/2
This changes the pa11y task to not require `obt demo` to have been run first by the user.
> Make pa11y run against all supported brands and build the pa11y demo before it runs

- lib/tasks/pa11y.js
Currently the ignorebower flag is not passed through which is making the pa11y test fail for the npm version of our components
> pass through the ignore bower flag when building the pa11y demo

- lib/tasks/verify-origami-json.js
- package-lock.json
- package.json
- test/integration/demo/fixtures/multiple-demos/origami.json
- test/integration/verify/fixtures/js-bower-dependency/origami.json
- test/integration/verify/fixtures/js-custom-eslint/origami.json
- test/integration/verify/fixtures/js-es5/origami.json
- test/integration/verify/fixtures/js-es6/origami.json
- test/integration/verify/fixtures/js-es7/origami.json
- test/integration/verify/fixtures/js-invalid/origami.json
- test/integration/verify/fixtures/js-npm-dependency/origami.json
- test/integration/verify/fixtures/no-js-or-sass/origami.json
- test/integration/verify/fixtures/no-readme/origami.json
- test/integration/verify/fixtures/readme-custom-remarkrc/origami.json
- test/integration/verify/fixtures/readme-invalid-name/origami.json
- test/integration/verify/fixtures/readme-invalid/origami.json
- test/integration/verify/fixtures/readme-valid-lowercase/origami.json
- test/integration/verify/fixtures/readme-valid-uppercase/origami.json
- test/integration/verify/fixtures/sass-bower-dependency/origami.json
- test/integration/verify/fixtures/sass-custom-config/origami.json
- test/integration/verify/fixtures/sass-invalid/origami.json
- test/integration/verify/fixtures/sass-npm-dependency/origami.json
- test/integration/verify/fixtures/sass/origami.json
- test/unit/fixtures/o-test/origami.json
- test/unit/tasks/verify-origami-json.test.js
Rather than v1, which will not be supported in the next major version
of Origami Build Tools
> Verify the component follows v2 of the Origami component specification.

- .github/workflows/publish-to-npm-as-latest.yml
- .github/workflows/publish-to-npm-as-prerelease.yml
Prior to this change, every release would be given the dist-tag `latest`, which is not what we want. We only want stable releases to be given the `latest` dist-tag.
I've changed the trigger for the workflows to no longer be on a created release but instead when a tag is pushed, this is because you can not filter on a release trigger but you can filter on a pushed tag.
Here is the documentation for filters --> https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
> Add ability to publish prereleases with a different dist-tag.

- .github/workflows/automatic-tag-and-release.yml
Same as https://github.com/Financial-Times/origami-build-tools/pull/952 but targeted at the v11 branch
https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token
> Currently we are using the read-only github token. When using this token and pushing commits/tags to github, github will not trigger any workflows for the pushed commit/tag.
> 
> We need the pushed tag to trigger out npm-publishing workflows, which means we need to use a custom github token instead of the default token provided by github actions.
> Make git pushes in create-new-version workflow trigger other workflows

- test/unit/tasks/pa11y.test.js
There was a changed in pa11y where it started to use console.warn, which is a method that doesn't exist in our current mock console and as such was throwing an error when testing.
We need to fix this to unblock other obt pull-requests such as this one https://github.com/Financial-Times/origami-build-tools/pull/955
> Add missing methods to the mock console used in pa11y tests

- lib/helpers/files.js
- lib/tasks/demo-build.js
- lib/tasks/pa11y.js
- test/unit/helpers/files.test.js
- test/unit/tasks/demo-build.test.js
- test/unit/tasks/pa11y.test.js
pa11y tests should run if there is a demo with name `pa11y` which
compiles to `pa11y.html` in the demos directory. The demo may or
may not be based on a template `pa11y.mustache`.
This commit also removes references to "custom config" (it would
have been awkward to commit separately). Custom config is a way
of configuring components outside of origami.json. This is not
documented anywhere in spec v1, moving to spec v2 is a good time
to drop suppport.
> Run pa11y tests when there is no `pa11y.mustache` template.

- lib/helpers/files.js
- lib/tasks/pa11y.js
- test/unit/config/karma-config.test.js
- test/unit/helpers/files.test.js
we don't actually specify what the default brand is [if no brand is defined](https://origami.ft.com/spec/v1/manifest/#brands)...
We know it should be `master` though, so that is what this pull-request changes `getModuleBrands` to return if no brands are defined.
This also fixes a bug in the pa11y task where it would only run pa11y on the first brand defined for the component and not for all the brands defined.
> Make pa11y work on components which have no explicilty defined their brand support

- lib/helpers/files.js
- lib/helpers/verify-component-specification-version.js
- lib/origami-build-tools-cli.js
- test/integration/install/fixtures/no-npm-dependencies/origami.json
- test/integration/install/fixtures/non-existent-npm-dependency/origami.json
- test/integration/install/fixtures/with-npm-dependencies/origami.json
- test/integration/test/fixtures/with-npm-dependency-installed/origami.json
- test/unit/helpers/verify-component-specification-version.test.js
When running on a directory with no `origami.json`, or misconfigured
`origamiVersion` property:
> Is this an Origami component?
>
> Origami Build Tools may only be used to develop Origami
> components. It looks like this isn\'t an Origami component,
> or the component is missing a valid "origami.json". See the
> component specification for more details:
> https://origami.ft.com/spec/'
When running on a v1 component:
> This version of Origami Build Tools does not support components
> which follow v1 of the Origami component specification.
> To work on this component install a previous version of the
> Origami Build Tools (v10). Alternatively, upgrade this
> component to follow v2 or above of the Origami specification.
> See the component specification for more details:
> …
> Throw a helpful error when running outside a v2 component directory.

- lib/tasks/karma.js
- package-lock.json
- package.json
Newer versions of Karma throw an error if a file is supplied as a string instead of a file object.
Here we have updated our config to use the documented file object to ensure the newer versions of karma work with obt.
This is currently an issue everyone will hit if they are installing origami-build-tools for the first time because newer versions of karma will get installed (because we do not include an npm-shrinkwrap).
> fix bug in karma config due to misuing the karma api

- test/unit/tasks/verify-package-json.test.js
For the scenarios where we were testing an invalid package.json file, if verify-package-json incorrectly validated the package.json, the test would not fail.
I've refactored those tests to now check if verify-package-json has returned a rejected promise, and if it has not, to fail.
I've also refactored the code to use proclaim.deepStrictEqual instead of proclaim.calledWithExactly because deepStrictEqual will the expected value and actual value if they are not the same, whereas calledWithExactly only states they are not the same, which I did not find useful at all because I couldn't tell where/how they were different.
> Improve tests for verify-package-json

- lib/tasks/verify-package-json.js
- test/integration/demo/fixtures/multiple-demos/package.json
- test/integration/verify/fixtures/js-custom-eslint/package.json
- test/integration/verify/fixtures/js-es5/package.json
- test/integration/verify/fixtures/js-es6/package.json
- test/integration/verify/fixtures/js-es7/package.json
- test/integration/verify/fixtures/js-invalid/package.json
- test/integration/verify/fixtures/js-npm-dependency/package.json
- test/integration/verify/fixtures/no-js-or-sass/package.json
- test/integration/verify/fixtures/no-readme/package.json
- test/integration/verify/fixtures/readme-custom-remarkrc/package.json
- test/integration/verify/fixtures/readme-invalid-name/package.json
- test/integration/verify/fixtures/readme-invalid/package.json
- test/integration/verify/fixtures/readme-valid-lowercase/package.json
- test/integration/verify/fixtures/readme-valid-uppercase/package.json
- test/integration/verify/fixtures/sass-custom-config/package.json
- test/integration/verify/fixtures/sass-invalid/package.json
- test/unit/fixtures/o-test/package.json
- test/unit/tasks/verify-package-json.test.js
The component v2 specification states that if a main.js file exists, then the `browser` field must be set to `"main.js"`. This commit updates the verify task to ensure that the component being tested adheres to these rules.
I've quoted below the parts of the specification this is testing.
>  - It **must** include a <a href="https://docs.npmjs.com/cli/v7/configuring-npm/package-json#browser">`browser`</a> property set to the component's main JavaScript file (`main.js`) **_if_** it exists.
Those came from the spec v2 pull-request -- https://github.com/Financial-Times/origami-website/pull/273/files#diff-5ebc2f3b798414ec905f3fdceb910557607b8d779a56bf1ce09ad48e32fd085aR88
I've also added in a check for the opposite situation, if no `main.js` file exists, then the `browser` field should not …
> Add validation for package.json.browser field

- lib/tasks/verify-origami-json.js
- test/unit/tasks/verify-origami-json.test.js
When migrating ftdomdelegate we found that `obt verify` reports a failure because ftdomdelegate is listed as a library.
The three options I can think of to resolve this are:
1.  Make obt check for all the possible allowed values of origamiType
2.  Remove origamiType from the specification
3.  Remove obt from the projects which are not components, such as ftdomdelegate
> Make verify-origami-json look for all the different origamiType variations

- lib/tasks/verify-package-json.js
- test/unit/fixtures/o-test/package.json
- test/unit/tasks/verify-package-json.test.js
The component 2.0 states:
>  - It **must** include a <a href="https://nodejs.org/api/packages.html#packages_type">`type`</a> property set to `"module"`.
This pull-request adds this as a test in origami-build-tools to help component authors ensure their component follows the specification
> Ensure that origami components have package.json.type set to 'module'

- lib/tasks/verify-package-json.js
- test/unit/tasks/demo-build.test.js
- test/unit/tasks/verify-package-json.test.js
Currently obt will skip the package.json validation steps if no package.json exists.
As the specification states the file must exist, we should have obt fails validation if the file does not exist.
The below is from the 2.0 draft specification:
>Origami components **must** include the following files:
>
>  - `main.js` **_if_** the component has JavaScript functionality
>  - `main.scss` **_if_** the component has styles
>  - `origami.json` as outlined in [Origami.json manifest](#origamijson-manifest) above
>  - `package.json` as to ensure the component is installable via the <a href="https://npmjs.com/" class="o-typography-link--external">npm package manager</a>
> Enforce that a package.json file exists for origami components instead of skipping the validation

- lib/tasks/verify-package-json.js
- npm-shrinkwrap.json
- package.json
- test/integration/install/fixtures/non-existent-npm-dependency/package.json
- test/integration/install/fixtures/with-npm-dependencies/package-lock.json
- test/integration/install/fixtures/with-npm-dependencies/package.json
- test/integration/test/fixtures/with-npm-dependency-installed/package-lock.json
- test/integration/test/fixtures/with-npm-dependency-installed/package.json
- test/integration/verify/fixtures/js-custom-eslint/package.json
- test/integration/verify/fixtures/js-es5/package.json
- test/integration/verify/fixtures/js-es6/package.json
- test/integration/verify/fixtures/js-es7/package.json
- test/integration/verify/fixtures/js-invalid/package.json
- test/integration/verify/fixtures/js-npm-dependency/package.json
- test/integration/verify/fixtures/no-js-or-sass/package.json
- test/integration/verify/fixtures/no-readme/package.json
- test/integration/verify/fixtures/readme-custom-remarkrc/package.json
- test/integration/verify/fixtures/readme-invalid-name/package.json
- test/integration/verify/fixtures/readme-invalid/package.json
- test/integration/verify/fixtures/readme-valid-lowercase/package.json
- test/integration/verify/fixtures/readme-valid-uppercase/package.json
- test/integration/verify/fixtures/sass-custom-config/package.json
- test/integration/verify/fixtures/sass-npm-dependency/package.json
- test/integration/verify/fixtures/sass/package.json
- test/unit/fixtures/o-test/package.json
- test/unit/tasks/verify-package-json.test.js
This verification helps ensure origami components adhere to the specification
The origami 2.0 spec states:
>It *must* include an engines property set to an object which has an npm property set to a SemVer range which disallows anything below v7.0.0. E.G. ^7 would be valid as would >= 7.
> Verify supported npm version is set to a minimum of 7.0.0

- npm-shrinkwrap.json
- package.json
- test/integration/demo/fixtures/multiple-demos/origami.json
- test/integration/install/fixtures/no-npm-dependencies/origami.json
- test/integration/install/fixtures/non-existent-npm-dependency/origami.json
- test/integration/install/fixtures/with-npm-dependencies/origami.json
- test/integration/test/fixtures/with-npm-dependency-installed/origami.json
- test/integration/verify/fixtures/js-custom-eslint/origami.json
- test/integration/verify/fixtures/js-es5/origami.json
- test/integration/verify/fixtures/js-es6/origami.json
- test/integration/verify/fixtures/js-es7/origami.json
- test/integration/verify/fixtures/js-invalid/origami.json
- test/integration/verify/fixtures/js-npm-dependency/origami.json
- test/integration/verify/fixtures/no-js-or-sass/origami.json
- test/integration/verify/fixtures/no-readme/origami.json
- test/integration/verify/fixtures/readme-custom-remarkrc/origami.json
- test/integration/verify/fixtures/readme-invalid-name/origami.json
- test/integration/verify/fixtures/readme-invalid/origami.json
- test/integration/verify/fixtures/readme-valid-lowercase/origami.json
- test/integration/verify/fixtures/readme-valid-uppercase/origami.json
- test/integration/verify/fixtures/sass-custom-config/origami.json
- test/integration/verify/fixtures/sass-invalid/origami.json
- test/integration/verify/fixtures/sass-npm-dependency/origami.json
- test/integration/verify/fixtures/sass/origami.json
https://github.com/Financial-Times/origami/pull/120
> Remove "origamiCategory", it is no longer part of spec v2 components.

- npm-shrinkwrap.json
- package.json
There is a known issue with mixing npm 7 and npm 6 installs which makes the generated shrinkwrap/lockfile have missing hasInstallScript properties -- https://github.com/npm/cli/issues/2606
The currently released beta of obt 11 fails to install esbuild correctly due to this bug, because esbuild's installation script is not getting executed
> recreate the shrinkwrap to add the missing hasInstallScript sections from our dependencies

- .gitignore
- npm-shrinkwrap.json
- package.json
- test/integration/demo/demo.test.js
- test/integration/helpers/tmpdir.js
- test/integration/init/init.test.js
- test/integration/test/test.test.js
- test/integration/verify/verify.test.js
- test/unit/tasks/init.test.js
OBT previously had three methods of creating temporary directories
to run tests in. Now each test uses the same helper. Temporary
directories are created within the obt integration test directory
which avoids cluttering our home directory and sidesteps any issues
with the temporary directory `os.tmpdir` we were seeing with Github
Actions.
> Update integration test temporary path. 

- templates/page.mustache
Previously the demo javascript would load in before the dependencies javascript.
By swapping the order around, the demo javascript can now make use any variables the dependency javascript creates, such as `window.Origami` which contains all the dependencies' JS exports.
> load the demo's dependency javascript before the demo's own javascript to ensure the dependecies are available to be used

- README.md
- lib/helpers/verify-component-specification-version.js
- lib/tasks/demo-build.js
- lib/tasks/demo.js
- lib/tasks/test-sass-compilation.js
- lib/tasks/verify-origami-json.js
- lib/tasks/verify-package-json.js
- test/unit/tasks/demo-build.test.js
- test/unit/tasks/verify-origami-json.test.js
- test/unit/tasks/verify-package-json.test.js
We decided to deprecate the Origami specification rather than
release v2.
Links to the Origami website 404 currently. Depends on:
Financial-Times/origami-website#361
> Remove spec v2 references

- lib/tasks/test-sass-compilation.js
- test/integration/test/test.test.js
Libraries may not have primary mixins. We would still expect them
to only output CSS when their Sass API is called though, not by
default on import.
> Update test command to only expect primary Sass mixins for components.

- lib/tasks/test-sass-compilation.js
Not all components provide css by default for a particular brand, for example o-fonts' whitelabel mode has no css.
Percy's visual testing catches any regression a component would have if it used to produce css and no longer does
> Remove requirement that the primary mixin produces css by default

- lib/tasks/test-sass-compilation.js
- test/integration/test/test.test.js
currently there is a bug in the test-sass-compilation module where it would try and run sass tests on libraries which have no sass such as o-autoinit and o-errors. This fixes the bug 👍
> do not run sass compilation test if there is no main sass file

- lib/tasks/pa11y.js
`origami-ci-tools` runs `obt test --ignore-bower`, to test the
npm package of a component which supports Bower and npm is correct:
https://github.com/Financial-Times/origami-ci-tools/blob/master/commands/branch.js#L52
This used to not run pa11y tests as the pa11y demo is not built by
`origami-ci-tools`, and Origami Build Tools used to skip pa11y tests
if a built pa11y demo was not found. However origami-build-tools
was updated to check for pa11y source code and build the pa11y
demo if it exists:
https://github.com/Financial-Times/origami-build-tools/pull/933/files#diff-6c44fc3cf122c89eee3ab192bd97d1a853d25adb56fa750332e79aac7ad230d4R90
`origami-component-converter`, used to generate the npm bundle, does
not support demo source code so the pa11y build fails, and thus
`origami-ci-tools` …
> Skip pa11y tests when the `--ignore-bower` flag is set.

- lib/helpers/files.js
- lib/tasks/demo-build.js
- lib/tasks/test-sass-compilation.js
- lib/tasks/verify-javascript.js
- lib/tasks/verify-origami-json.js
- lib/tasks/verify-package-json.js
- lib/tasks/verify-readme.js
- lib/tasks/verify-sass.js
- test/integration/helpers/fileExists.js
- test/integration/verify/verify.test.js
NodeJS is deprecating the automatic closing of fileHandlers during garbage collection.
This commit updates the codebase to explicitly close the fileHandlers instead of relying on the deprecated behaviour.
Below is the message that is displayed when running obt prior to this commit:
>DeprecationWarning: Closing a FileHandle object on garbage collection is deprecated. 
>Please close FileHandle objects explicitly using FileHandle.prototype.close().
>In the future, an error will be thrown if a file descriptor is closed during garbage collection.
> close the filehandler that fileExists creates
