Financial-Times/origami-build-tools

lib/tasks/build.js
lib/tasks/docs.js
lib/tasks/verify.js
package.json

An new pull request just for this fix.

Fix early finish for build task

---

README.md
config/scss-lint.yml
gulpfile.js
lib/tasks/verify.js
package.json
test/fixtures/o-test/scss-lint.yml
test/tasks/verify.test.js

Added custom fail reporter so build does not fail with warnings

---

README.md
lib/tasks/install.js

@AlbertoElias @kaelig @matthew-andrews

verbose output for npm

---

.travis.yml

Make travis go faster

---

README.md
lib/tasks/build.js

added ability to configure css clean

---

TROUBLESHOOT.md
lib/tasks/build.js
lib/tasks/demo.js
lib/tasks/install.js
lib/tasks/watch.js
package.json
templates/page.mustache

Improves instructions when obt install fails

---

lib/tasks/demo.js

Livereload

---

config/.eslintrc

I _think_ this makes it consistent with jshint config

don't allow overwriting of globals [consistent with obt]

---

lib/helpers/update-notifier.js

Better sudo explanation

---

TROUBLESHOOT.md

Fixes to troubleshooting guide, summary:
* Remove sudo mentions
* Add node install guide with permission changes
* Add guide to installing ruby with rbenv and ruby-build, git checkout guide
* Remove npm err! argv 
* Move Error Unable to download data... to bottom
* Add git protocol fix
CC @triblondon

Troubleshoot fixes

---

TROUBLESHOOT.md

Official website instead of archived guide.

Update node install link in troubleshoot guide

---

package.json

Fix stream-combiner at 1.0.2

---

README.md
lib/tasks/build.js
package.json

This builds a source map as a separate file, with development file paths hard coded so far.
I'm gonna work on creating what we need for next. Please leave comments about the requirements for the wider origami community in here and I'll try to accommodate both @AlbertoElias

Building source maps using webpack

---

lib/plugins/babelRuntimePathResolver.js

cc/ @matthew-andrews @AlbertoElias

NPM 3 compatible version of babelPathResolver

---

README.md
lib/tasks/build.js

Create sass source maps in external file

---

lib/plugins/babelRuntimePathResolver.js

Resolve babel-runtime on the fly

---

lib/tasks/verify.js
package.json

fixes #325 by updating stream-combiner2 and using .obj

---

lib/tasks/build.js

Removes inline sass sourcemaps unsupported message

---

lib/tasks/build.js

Need to `init` sourceMaps before sass compilation

Fix sass source map creation

---

lib/tasks/build.js

http://caniuse.com/#search=box-sizing

Autoprefix for bb7+

---

lib/tasks/build.js

let babel-runtime be disabled

---

templates/page.mustache

https://github.com/Financial-Times/origami-build-tools/issues/359

Add a lang attribute to demos

---

package.json

It's breaking modules, we need time to update them

Lock down node-sass due to new rule re imports

---

README.md
lib/origami-build-tools-cli.js

- Fix grammar "mostly used" -> "most used"
- Change a whitespace character that's breaking markdown
- Document the babelRuntime flag
@AlbertoElias are you happy of this discription of what babelRuntime=false does?

Update readme, fix grammar

---

lib/tasks/demo.js

Fixes #368
Looks like the issue was with requiring json and then mutating it

Fix bug with shared demo json

---

templates/page.mustache
test/tasks/demo.test.js

update the polyfill domain and version from v1 to v2

---

README.md
lib/tasks/build.js
package.json

https://github.com/Financial-Times/origami-build-tools/issues/400

Stop polyfills from being included via OBT

---

package.json
test/tasks/build.test.js

some more dependencies which can be updated :-)

Update deps once again

---

lib/origami-build-tools-cli.js
package.json

Swap to meow to enable simpler cli parsing, printing and aliasing

---

lib/origami-build-tools.js
lib/tasks/version.js

Remove bespoke version task as is handled by meow

---

package.json

Previously this was pointing to a non-existent file.

Reference the actual main file

---

lib/tasks/build-js.js
lib/tasks/demo-build.js
package-lock.json

This prevents parallel builds overriding previous build config.

Clone webpack config for each js build.

---

.travis.yml
package.json

(note merging into 8.x branch)

Require Node.js 8.x

---

.eslintrc.js
lib/tasks/pa11y.js
package-lock.json
package.json

Easier to understand the [changes with whitespace ignored](https://github.com/Financial-Times/origami-build-tools/pull/516/files?w=1)

Use Pa11y 5.x

---

lib/tasks/demo.js
package-lock.json
test/helpers/files.test.js

This passes the `brand=internal` (or any brand) parameter through to the demo build, so that we can change this through the url.

Branding param

---

config/karma.config.js
test/unit/config/karma-config.test.js

We build Sass in _all_ the places.

Include `$system-code` in Karma Sass build.

---

lib/tasks/run-bower-install.js
test/unit/tasks/run-bower-install.test.js

Working around https://github.com/sindresorhus/execa/issues/169

use local node_modules bin directory to look for bower

---

package-lock.json
package.json
test/unit/tasks/demo-build.test.js

https://github.com/Financial-Times/origami-build-tools/issues/675

Upgrade Sinon

---

package-lock.json
package.json

figures breaking changes:
Require Node.js 8 027e8ae

update figures to latest

---

package-lock.json
package.json

breaking change from log-update:
v4.0.0
Require Node.js 10 c0dbd25
v3.0.0
Require Node.js 6 fcb241a

update log-update to latest version

---

lib/tasks/test-sass.js
package.json

This is not needed within node 12

Remove `promise.prototype.finally`

---

config/karma.config.js
lib/tasks/demo.js
lib/tasks/init.js
lib/tasks/install-bower.js
lib/tasks/install-npm.js
lib/tasks/install.js
lib/tasks/test-sass.js
lib/tasks/test.js
lib/tasks/verify.js

This will speed up all the tasks :-D

use listr-multiline-renderer on all tasks and run all tasks' jobs concurrently

---

lib/tasks/demo-build.js

https://github.com/Financial-Times/origami-build-tools/issues/737

Pass ignoreBower flag through from demo to sass and js tasks

---

lib/tasks/test-sass-compilation.js
lib/tasks/test.js

Make the sass compilation tests be a nested Listr

---

package-lock.json
package.json
test/unit/fixtures/verify/src/scss/space-after-comma/valid.scss

This should be valid:
```scss
.argument-newline {
@include baz(
'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
'Lorem ipsum dolor sit amet consectetur adipisicing.'
);
}
```

Allow function arguments to go on a new line.

---

.snyk
lib/tasks/test-sass.js
package-lock.json
package.json
test/integration/test/fixtures/with-bower-dependency-installed/test/scss/_mixins.test.scss
test/integration/test/fixtures/with-bower-dependency-installed/test/scss/index.test.scss
test/integration/test/fixtures/with-npm-dependency-installed/test/scss/_mixins.test.scss
test/integration/test/fixtures/with-npm-dependency-installed/test/scss/index.test.scss

Relates to:
https://github.com/Financial-Times/origami-build-tools/pull/856

True removed support for node-sass in v6.

---

origami.json

https://origami.ft.com/spec/v1/manifest/#origamitype

Update origamiType to cli
